version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: box_billing
    container_name: bb_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: bb_web
    restart: unless-stopped
    tty: true
    ports:
      - "8004:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  #image: hypriot/rpi-mysql:latest
  db:
    image: mysql
    container_name: bb_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_DATABASE: boxbilling
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo
      MYSQL_ROOT_PASSWORD: foo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
      driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
